"""initial

Revision ID: d3571e3efbb4
Revises: 
Create Date: 2025-09-23 17:43:48.503582

"""
from typing import Sequence, Union
import sqlmodel
from sqlalchemy import String
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3571e3efbb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommended_products')
    op.drop_table('user_addresses')
    op.drop_table('additional_products')
    op.drop_table('users')
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'description',
                    existing_type=sa.TEXT(),
                    type_=String(),
                    existing_nullable=True)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('product_categories', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.alter_column('product_discounts', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_discounts', 'discount_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('product_discounts', 'valid_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_discounts', 'valid_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_product_discounts_id'), table_name='product_discounts')
    op.alter_column('product_images', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
                    existing_type=sa.TEXT(),
                    type_=String(),
                    existing_nullable=True)
    op.execute("UPDATE products SET is_active = true WHERE is_active IS NULL")
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('stock_records', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_records', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('stock_records', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_records', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_stock_records_id'), table_name='stock_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_records_id'), 'stock_records', ['id'], unique=False)
    op.alter_column('stock_records', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stock_records', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_records', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('stock_records', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.alter_column('product_images', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_product_discounts_id'), 'product_discounts', ['id'], unique=False)
    op.alter_column('product_discounts', 'valid_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_discounts', 'valid_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_discounts', 'discount_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('product_discounts', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.alter_column('product_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_categories', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_temporary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('additional_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('primary_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('additional_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['additional_id'], ['products.id'], name=op.f('additional_products_additional_id_fkey')),
    sa.ForeignKeyConstraint(['primary_id'], ['products.id'], name=op.f('additional_products_primary_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('additional_products_pkey'))
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('house', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('apartment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_addresses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_addresses_pkey'))
    )
    op.create_table('recommended_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('primary_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recommended_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['primary_id'], ['products.id'], name=op.f('recommended_products_primary_id_fkey')),
    sa.ForeignKeyConstraint(['recommended_id'], ['products.id'], name=op.f('recommended_products_recommended_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommended_products_pkey'))
    )
    # ### end Alembic commands ###
